"""Runtime compatibility shims for third-party predictor dependencies.

These patch *other people's* libraries, which is not something to do lightly, so
each shim here follows the same rules: it targets one known upstream
incompatibility, it probes for the fault rather than assuming it, it is a no-op
when the dependency is already correct, and it reports what it did.

The alternative approaches were considered and rejected:

* **Editing ``site-packages`` by hand** works until the next
  ``pip install``/``conda env create``, is invisible to collaborators, and makes
  the environment unreproducible from its own spec — the failure comes back on
  the next machine.
* **Vendoring a patched fork as a git submodule** is disproportionate for a
  one-line upstream bug, and does not actually take effect: ``jax_unirep`` is a
  *transitive* dependency (``amylodeep`` → ``jax_unirep``), resolved by pip/conda
  from the index, so a submodule in this repository is simply not what gets
  imported. You would have to force-install the fork over the resolved one,
  which fights the package manager on every environment rebuild.
* **Pinning older versions** is the cleanest fix in principle, and is what should
  be done if a compatible pin exists. It does not here: the ``a_min`` spelling
  was removed from JAX in the same era that NumPy 2.0 renamed it, and the
  affected environments run recent Python (3.12–3.14) where those old JAX builds
  have no wheels.

So: a narrow runtime patch, applied by the runner that needs it, with the real
fix being upstream.
"""

from __future__ import annotations

import warnings


def patch_jax_unirep_clip() -> bool:
    """Repair ``jax_unirep.activations.safe_sigmoid_exp`` for NumPy 2 / modern JAX.

    ``jax_unirep`` calls ``jax.numpy.clip(x, a_min=-88)``. NumPy 2.0 renamed
    ``clip``'s bounds from ``a_min``/``a_max`` to ``min``/``max``, JAX followed,
    and the keyword was removed — so every call raises::

        TypeError: clip() got an unexpected keyword argument 'a_min'

    which surfaces deep inside ``mLSTMCell`` and makes AmyloDeep's UniRep model
    unusable. There is exactly one such call in the package.

    The replacement is numerically identical for every real call site (verified
    against the pre-NumPy-2 behaviour) and additionally honours ``clip_value``,
    which the original accepts but ignores.

    Returns True if a patch was applied, False if the dependency was already
    correct or is not installed.
    """
    try:
        import jax.numpy as jnp
        import jax_unirep.activations as activations
    except ImportError:
        return False

    # Already patched by an earlier call: the probe below tests jnp.clip, which
    # stays broken after we replace jax_unirep's function, so without this marker
    # every call would re-patch and re-warn.
    if getattr(activations.safe_sigmoid_exp, "_aggressor_patched", False):
        return False

    probe = jnp.array([0.0])
    try:
        jnp.clip(probe, a_min=-88)
        return False  # upstream is fine; leave it alone
    except TypeError:
        pass

    def safe_sigmoid_exp(x, clip_value=-88):  # noqa: D401 - mirrors upstream
        """Clipped exp-sigmoid, using positional bounds (NumPy 2 compatible)."""
        return 1 / (1 + jnp.exp(-jnp.clip(x, clip_value)))

    safe_sigmoid_exp._aggressor_patched = True
    activations.safe_sigmoid_exp = safe_sigmoid_exp
    warnings.warn(
        "Patched jax_unirep.activations.safe_sigmoid_exp: the installed "
        "jax_unirep calls jnp.clip(a_min=...), which NumPy 2 / modern JAX "
        "removed. The patch is numerically equivalent. The durable fix is "
        "upstream in jax_unirep.",
        RuntimeWarning,
        stacklevel=2,
    )
    return True


# --------------------------------------------------------------------------- #
# Cross-process form of the same fix
# --------------------------------------------------------------------------- #

BOOTSTRAP_SOURCE = '''#!/usr/bin/env python3
"""Launch AmyloDeep with the jax_unirep clip fix applied in-process.

Generated by aggressor-wrappers. The fix has to live in the *same* interpreter
that runs the model, so patching from the calling process would have no effect —
AmyloDeep runs as a subprocess, usually in its own conda environment. This
bootstrap is therefore self-contained: it imports nothing from
aggressor-wrappers and can be run by any interpreter that has AmyloDeep.

Upstream bug: jax_unirep calls jnp.clip(x, a_min=-88); NumPy 2.0 renamed clip's
bounds to min/max and JAX followed, removing the keyword. One call site.
"""
import sys


def _patch():
    try:
        import jax.numpy as jnp
        import jax_unirep.activations as activations
    except ImportError:
        return
    if getattr(activations.safe_sigmoid_exp, "_aggressor_patched", False):
        return
    try:
        jnp.clip(jnp.array([0.0]), a_min=-88)
        return
    except TypeError:
        pass

    def safe_sigmoid_exp(x, clip_value=-88):
        return 1 / (1 + jnp.exp(-jnp.clip(x, clip_value)))

    safe_sigmoid_exp._aggressor_patched = True
    activations.safe_sigmoid_exp = safe_sigmoid_exp


if __name__ == "__main__":
    _patch()
    from amylodeep.cli import main

    sys.argv = ["amylodeep"] + sys.argv[1:]
    sys.exit(main())
'''


def write_amylodeep_bootstrap(dest):
    """Write the self-contained AmyloDeep launcher; return its path."""
    from pathlib import Path

    path = Path(dest)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(BOOTSTRAP_SOURCE, encoding="utf-8")
    return path
